### ISSUE TITLE
Flow or screens when signing up to apply on an opportunity

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#125]
Just tried this in platform-dev:

- Not signed in
- Clicked on Apply button on an opportunity
- was taken to the Sign Up page 👍 
- Signed in with GitHub 👍 
- Signed in successfully, but was taken back to homepage 😢  .... Can we make it go back to the opportunity I was on? 

Also found that when I navigated back to the opportunity, the Apply button was not there anymore... (maybe this is because I am a gov user?)

**Comment by ccoldwell** [comment]
- yes, if you are a gov user you cannot apply for an opportunity

**Comment by mark-a-wilson** [comment]
OK, so that part's not a bug...but can you change it so that Sign Up takes the user back to the page they were just viewing?
(And can you set me up with a username and password for a non-gov user that I can use for platform-dev and platform-test?)

**Comment by ccoldwell** [comment]
OK, I have a potential fix for the 'take me back to that page' issue, but it may not be 100%.  The problem is that it is not an interrupted flow, like when you try to access a page with security. We are actually sending them explicitly to the signin page.  Anyhow, I have a hack that *might* work, we will see. If the user takes a different path though it will fail.

**Comment by ccoldwell** [comment]
the easiest thing for testing is to log in as admin and remove the 'gov' role from your mark.wilson account.  Play around as mark for a bit, then put the role back on later

**Comment by mark-a-wilson** [comment]
We agreed today this may not be critical for now. Marking it as an enhancement for the backlog.

**Comment by mark-a-wilson** [comment]
Added to backlog on DevX App Trello board.
