### ISSUE TITLE
Unable to click on Attachments tab until the proposal has been saved

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#163]

**Comment by ccoldwell** [comment]
This is intended. There does not yet exist a proposal to attach things to until you save the proposal

**Comment by mark-a-wilson** [comment]
Loren and I are of the same opinion that this will be unintuitive for users. (As a user, it may not be intuitive that I have to 'save' my blank proposal before I can upload a document.) Is it difficult to remove that rule?

**Comment by ccoldwell** [comment]
We can simply hide the tab until they have saved. It is literally the case
that until the proposal is saved there is nothing to attach the uploaded
files to.  To reverse the process we would have to put the files into some
sort of limbo somewhere, or simply not upload them until save (which I am
not sure how to do or even if that is possible).  This is all because
uploads happen instantly and they are keyed by the proposal id.

So I would suggest we simply hide the upload tab until they have saved, or
put a message on hover that uploads are possible after save

Either way is fine just let me know your preference

C

**Comment by mark-a-wilson** [comment]
OK, I'm OK with hiding the tab until they have saved. @lmullane ?

**Comment by lmullane** [comment]
I'm good with the hide until they save as they can't submit without saving first.
