### ISSUE TITLE
Allow users to manage their affiliation with a company

### ISSUE THREAD

**Issue by kriscooke** [BCDevExchange/devex#431]
While only a company admin can add members to a company, those members should be able to manage their own affiliations via the ability to remove themselves from a company.

**Comment by mark-a-wilson** [comment]
We have added this feature now. If you navigate to your Settings > Company Affiliations, you'll see a list of companies that you have been added to, with the option to 'Leave'. Also, we're handling company invitations now so that you receive an email invitation with the option to Accept or Decline. Thanks for prodding us way back in July to add this!
