### ISSUE TITLE
DevOps Improvements for the BC Developers' Exchange

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#577]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-database-and-devops-improvements-for-the-bc-developer-s-exchange"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-database-and-devops-improvements-for-the-bc-developer-s-exchange">visit the opportunity page</a>.
The opportunity closes on <b>Tuesday, March 19th, 2019 at 16:00 PDT</b>.</p>

**Comment by sutherlanda** [comment]
We've updated this opportunity due to a lack of support for HA MongoDB configurations in OpenShift.  Instead, we will be looking for someone to update the Developers' Exchange application to gracefully handle the application and database containers being brought offline and online.  If you have any questions, please let us know by responding in this thread or by sending email to bcdevexchange@gov.bc.ca.  Thank you!

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by sutherlanda** [comment]
Thank you to everyone who submitted proposals for this opportunity.  We received a total of 4 proposals, and have assigned the opportunity.  If you would like feedback on your proposal, please feel to request via email (address in my profile).
