### ISSUE TITLE
Program Members

### ISSUE THREAD

**Issue by DavidR8** [BCDevExchange/devex#83]
Program Member section on Program pages don't show any of the associated people.

**Comment by mark-a-wilson** [comment]
@DavidR8 - unfortunately this is going to be a limitation for the soft launch, because in order to show members, we have to get those individuals to sign in to the app first. I will discuss whether we want to hide the program members for soft launch.

ref https://github.com/BCDevExchange/devex/issues/57

**Comment by mark-a-wilson** [comment]
we've decided to keep members shown

**Comment by lmullane** [comment]
@MeaghanRStewart, may have a list of all the members from the various teams. Might be handy to put out the call for them to join.
